# Logging
logging:
  level:
    com.example.demo: trace

# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:demo
      username: sa
      password:
    sql-script-encoding: UTF-8
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    in-memory: true
swagger:
  enabled: true

jwt:
  secret: KB2019!@
kakao:
  appKey: c9f6f5f7a8870db204e7aca892b86c7c
  apiUrl: https://dapi.kakao.com/v3/search/book

