# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### /users/login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "user",
  "password": "111111"
}

> {%
client.global.set("authToken", response.body.authToken);
%}

### /users/login
GET http://localhost:8080/users/me
Authorization: {{authToken}}
Content-Type: application/json

### /book-search
OPTIONS http://localhost:8080/book-search
Content-Type: application/json
Orgin: http://test.com
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET

###
