# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### /users/login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "user",
  "password": "111111"
}

> {%
client.global.set("authToken", response.body.authToken);
%}

### /users/login
GET http://localhost:8080/users/me
Authorization: {{authToken}}
Accept: application/json

### kakao
GET https://dapi.kakao.com/v3/search/book?query=미움받을 용기&page=1&size=10
Authorization: KakaoAK c9f6f5f7a8870db204e7aca892b86c7c

### naver
GET https://openapi.naver.com/v1/search/book.json?query=미움받을 용기&display=10&start=1
X-Naver-Client-Id: JyLp8UQf3BwFuGIqAFPE
X-Naver-Client-Secret: ZpYoyAfOWE


### /book-search
GET http://localhost:8080/book-search?query=Clean&size=10
Authorization: {{authToken}}
Content-Type: application/json

###
